# Generic settings about the mod
[general]
    # Set to "DISCORD" after configuring the discordBot section below
    mode = "NONE"
    # Should the crash reporter module be enabled.
    # To enable this, set the value from 'false' to 'true' and configure the webhook URL below in the [crash_report] section
    crash_reports_enabled = false

# Settings for the chat link when in Discord mode.
[discordBot]
    # Create a app at https://discord.com/developers/applications, add a bot and then copy the token here
    token = ""
    # The Discord webhook URL to send the Minecraft chat to
    webhook = ""
    # The ID of the channel to listen for messages to send to Minecraft.
    message_channel = ""

    # The icon to use for server messages (join, leave, etc)
    # Default is a grass block icon.
    server_icon = "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/93/Grass_Block_JE7_BE6.png/revision/latest?cb=20200830143209&format=original"

# Allowed mentions for chat messages being forwarded to Discord
[discordBot.allowedMentions]
    # Allow @everyone and @here
    everyone = false
    # Allow mentioning users
    users = true
    # Allow mentioning roles
    roles = true

# Misc settings used by multiple components
[misc]
    # Change the service used for player avatars.
    # Will be used like: <profileEndpoint> + <player uuid> + "?overlay=" + <player helmet skin layer active>
    profileEndpoint = "https://minotar.net/helm/"

# Settings for the Discord crash reporter
[crash_report]
    # The URL of the Discord webhook to send crash notifications
    webhook = ""
    # The username to display on the webhook message
    webhook_name = "Server crash reporter"
    # The URL to the icon for the webhook
    # Default is a grass block icon.
    webhook_icon = "https://static.wikia.nocookie.net/minecraft_gamepedia/images/9/93/Grass_Block_JE7_BE6.png/revision/latest?cb=20200830143209&format=original"
    # The name of the server to use in messages
    server_name = "Minecraft server"

# Settings for the /home command
[homes]
    # Should the command be enabled
    enabled = false
    # Should players be allowed to use homes to travel across dimensions
    allow_cross_dimension = true
    # Maximum amount of homes a player can have
    # Set to -1 for unlimited
    max_home_amount = 3
    # Should the maximum homes count be per-dimension (true), or across all dimensions (false)
    maxHomesPerDimension = false
